# Generated by Django 4.2.6 on 2024-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_chat_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departmant',
            field=models.CharField(choices=[('Job Seekers', 'Job'), ('Employers', 'Employers'), ('Sales_Department', 'Sales'), ('HR_Department', 'HR'), ('Developers', 'Coders'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
    ]
