# Generated by Django 4.2.6 on 2024-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_user_departmant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(max_length=220)),
                ('posted_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
